# Generated by Django 2.2.7 on 2020-08-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_checkout_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='customer',
        ),
    ]
