# Generated by Django 2.2.7 on 2020-08-06 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_help_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='customer',
        ),
        migrations.AddField(
            model_name='help',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
