# Generated by Django 2.2.7 on 2020-08-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200806_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='user',
        ),
    ]
